import Foundation

/// Generates the Spaces-managed Ghostty config for embedded terminals under
/// `<profile-root>/ghostty/`. Embedded surfaces load ONLY this generated config — never the
/// user's `~/.config/ghostty` files — so the default look stays predictable and matches the
/// active Spaces theme. The root config references one generated light and one generated dark
/// theme file; Ghostty's own light/dark switching (`ghostty_app_set_color_scheme`) picks the
/// variant, so an OS appearance change never requires regenerating files.
public enum GhosttyThemeConfigGenerator {
    /// Regenerates the config for the active profile and returns the root config file path.
    /// Called at every embedded-app start so the files always reflect the shipped theme values.
    public static func writeConfiguration(theme: ThemeDescriptor) throws -> String {
        let root = URL(fileURLWithPath: try SpacesProfile.current().rootDirectory, isDirectory: true).appendingPathComponent(
            "ghostty", isDirectory: true)
        let themesDirectory = root.appendingPathComponent("themes", isDirectory: true)
        try FileManager.default.createDirectory(at: themesDirectory, withIntermediateDirectories: true)

        let lightURL = themesDirectory.appendingPathComponent("\(theme.id.rawValue)-light", isDirectory: false)
        let darkURL = themesDirectory.appendingPathComponent("\(theme.id.rawValue)-dark", isDirectory: false)
        let configURL = root.appendingPathComponent("config", isDirectory: false)

        try themeFileContents(theme.light.terminal).write(to: lightURL, atomically: true, encoding: .utf8)
        try themeFileContents(theme.dark.terminal).write(to: darkURL, atomically: true, encoding: .utf8)
        try rootConfigContents(lightThemePath: lightURL.path, darkThemePath: darkURL.path).write(to: configURL, atomically: true, encoding: .utf8)
        return configURL.path
    }

    /// The root config: theme variant references plus the Spaces-owned embedded settings.
    /// `window-vsync = false` lets service-owned sessions render without a display-linked
    /// loop; `font-size = 12` pins embedded terminals to the app's text scale and matches
    /// the cell-metrics estimate the mirror view sizes with.
    static func rootConfigContents(lightThemePath: String, darkThemePath: String) -> String {
        """
        # Generated by Spaces at launch. Do not edit; changes are overwritten.
        theme = light:\(lightThemePath),dark:\(darkThemePath)
        window-vsync = false
        font-size = 12
        """ + "\n"
    }

    /// One Ghostty theme file (background/foreground, cursor, selection, 16-color palette).
    static func themeFileContents(_ terminal: GhosttyThemeExport) -> String {
        var lines = [
            "background = \(terminal.background.hexRGB)", "foreground = \(terminal.foreground.hexRGB)",
            "cursor-color = \(terminal.cursorColor.hexRGB)", "cursor-text = \(terminal.cursorText.hexRGB)",
            "selection-background = \(terminal.selectionBackground.hexRGB)", "selection-foreground = \(terminal.selectionForeground.hexRGB)",
        ]
        lines.append(contentsOf: terminal.palette.enumerated().map { index, color in "palette = \(index)=\(color.hexRGB)" })
        return lines.joined(separator: "\n") + "\n"
    }
}
