#!/bin/sh
set -eu

root="$(cd "$(dirname "$0")/.." && pwd)"
start_epoch="$(date +%s)"
cache_dir="$root/.build/clang-module-cache"
coverage_dir="$root/.build/coverage"
mkdir -p "$cache_dir"
mkdir -p "$coverage_dir"
export CLANG_MODULE_CACHE_PATH="$cache_dir"
export LLVM_PROFILE_FILE="$coverage_dir/%m.profraw"
export MOCK_TEST_DELAY_CAP_MS="${MOCK_TEST_DELAY_CAP_MS:-25}"

report_elapsed_time() {
    end_epoch="$(date +%s)"
    elapsed_seconds=$((end_epoch - start_epoch))
    echo "Coverage script elapsed: ${elapsed_seconds}s"
}
trap report_elapsed_time EXIT

echo "Running swift test with coverage..."
workers="${MUXY_TEST_WORKERS:-}"
if [ -z "$workers" ]; then
    detected_workers="$(sysctl -n hw.logicalcpu 2>/dev/null || echo "")"
    case "$detected_workers" in
        ''|*[!0-9]*)
            workers=""
            ;;
        *)
            workers="$detected_workers"
            ;;
    esac
fi

set -- test --parallel --enable-code-coverage --disable-sandbox
if [ -n "$workers" ]; then
    echo "Using parallel test workers: $workers"
    set -- "$@" --num-workers "$workers"
fi
if [ "${MUXY_TEST_SKIP_BUILD:-0}" = "1" ]; then
    echo "Skipping rebuild before tests (MUXY_TEST_SKIP_BUILD=1)"
    set -- "$@" --skip-build
fi

"$root/scripts/swiftpm.sh" "$@"

# Prefer the profdata generated by swift test --enable-code-coverage (placed in codecov/).
# Fall back to any profdata file sorted alphabetically only if not found.
profdata_path=$(find "$root/.build" -type f -name "default.profdata" -path "*/codecov/*" | sort | tail -n 1)
if [ -z "${profdata_path:-}" ]; then
    profdata_path=$(find "$root/.build" -type f -name "*.profdata" | sort | tail -n 1)
fi
if [ -z "${profdata_path:-}" ]; then
    echo "Coverage data not found. Expected a .profdata file under .build." >&2
    exit 1
fi

package_name=$(sed -n 's/^[[:space:]]*name:[[:space:]]*"\([^"]*\)".*/\1/p' "$root/Package.swift" | head -n 1)
expected_test_binary="${package_name}PackageTests"
test_binary=""
if [ -n "${package_name:-}" ]; then
    test_binary=$(find "$root/.build" -type f -path "*${expected_test_binary}.xctest/Contents/MacOS/${expected_test_binary}" | sort | tail -n 1)
fi
if [ -z "${test_binary:-}" ]; then
    test_binary=$(find "$root/.build" -type f -path "*PackageTests.xctest/Contents/MacOS/*PackageTests" | grep -v "\.dSYM" | sort | tail -n 1)
fi
if [ -z "${test_binary:-}" ]; then
    echo "Test binary not found under .build." >&2
    exit 1
fi

report_path="$coverage_dir/llvm-cov-report.txt"

echo "Coverage report:"
xcrun llvm-cov report \
    -instr-profile "$profdata_path" \
    --ignore-filename-regex="\\.build|/Tests/" \
    "$test_binary" | tee "$report_path"

echo "Coverage summary:"
awk '
BEGIN {
    module_order[1] = "streamctl"
    module_order[2] = "gui"
    module_order[3] = "appctl"
    module_order[4] = "muxycli"
}
/^TOTAL[[:space:]]/ {
    overall_lines = $10
}
/^(appctl|gui|streamctl|muxycli)\// {
    split($1, parts, "/")
    module = parts[1]
    regions_total[module] += $2
    regions_missed[module] += $3
    functions_total[module] += $5
    functions_missed[module] += $6
    lines_total[module] += $8
    lines_missed[module] += $9
}
END {
    if (overall_lines != "") {
        printf("  overall lines: %.2f%%\n", overall_lines + 0)
    }
    for (i = 1; i <= 4; i++) {
        module = module_order[i]
        if (lines_total[module] > 0) {
            line_cover = (lines_total[module] - lines_missed[module]) * 100 / lines_total[module]
            region_cover = (regions_total[module] - regions_missed[module]) * 100 / regions_total[module]
            function_cover = (functions_total[module] - functions_missed[module]) * 100 / functions_total[module]
            printf("  %s: lines %.2f%% | regions %.2f%% | functions %.2f%%\n", module, line_cover, region_cover, function_cover)
        }
    }
}
' "$report_path"

echo "Coverage report saved to: $report_path"
