import type { Metadata } from "next";
import { DocsShell } from "../components/docs-shell";

export const metadata: Metadata = {
  title: "FAQ",
  description: "Common questions about Spaceship behavior and boundaries.",
};

const faqs = [
  {
    q: "What is a workspace in Spaceship?",
    a: "A workspace is a stream of work with its own runtime context: process templates, browser sessions, status checks, captured windows, and reserved ports. For Git projects it is typically backed by a worktree.",
  },
  {
    q: "Where are workspace directories created?",
    a: "For Git projects, worktrees are created under /Users/<username>/spaceship/workspaces/<project>/<dirname>. The dirname is an autogenerated unique food-name token per project.",
  },
  {
    q: "Can I archive the default workspace?",
    a: "No. The default workspace is protected and cannot be archived.",
  },
  {
    q: "What happens when I archive a workspace?",
    a: "Archive runs the same stop flow as restart/stop, releases reserved ports, and marks the workspace archived. For Git projects, the worktree directory is removed but Git branches are kept.",
  },
  {
    q: "Does Spaceship manage window tiling and geometry?",
    a: "No. Spaceship manages window context and focus only. Tiling and geometry stay with yabai and your existing setup.",
  },
  {
    q: "How are browser tabs matched to a workspace?",
    a: "By URL prefix from browser session definitions. Spaceship intentionally avoids title-based matching to prevent false positives.",
  },
  {
    q: "Does Spaceship close my entire Chrome window when stopping a workspace?",
    a: "No. Browser cleanup closes matching tabs only, not entire Chrome windows.",
  },
  {
    q: "How are port conflicts handled?",
    a: "Each workspace reserves 10 ports (PORT0 through PORT9) from a configured range. Commands can consume those values via environment variables.",
  },
  {
    q: "Can workspace settings diverge from project templates?",
    a: "Yes. Workspace settings are copied from project templates at creation and then stored in SQLite. Workspace edits do not write back to YAML.",
  },
  {
    q: "What are Spaceship’s current browser and terminal targets?",
    a: "The spec defines Google Chrome for browser sessions and iTerm2 for process terminal windows.",
  },
  {
    q: "Can I customize keyboard shortcuts?",
    a: "Yes. Shortcut overrides are supported through the Settings view and corresponding CLI settings commands.",
  },
  {
    q: "Does Spaceship require editor plugins?",
    a: "No. Spaceship does not introspect editor internals and does not require VS Code extensions.",
  },
];

export default function FaqDocsPage() {
  return (
    <DocsShell
      title="FAQ"
      description="Answers to common questions about architecture decisions, lifecycle behavior, and daily workflow."
      pagePath="/docs/faq"
    >
      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Common Questions</h2>
        <div className="mt-4 space-y-4">
          {faqs.map((item) => (
            <section key={item.q} className="rounded-xl border border-line bg-surface/75 p-4">
              <h3 className="text-sm font-semibold text-foreground">{item.q}</h3>
              <p className="mt-2 text-sm leading-7 text-foreground-soft">{item.a}</p>
            </section>
          ))}
        </div>
      </article>

      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Non-Goals Recap</h2>
        <ul className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>• No tiling or geometry management.</li>
          <li>• No exact browser tab-order restoration guarantees.</li>
          <li>• No editor-internal automation or plugin requirement.</li>
          <li>• No secrets management beyond environment variables.</li>
        </ul>
      </article>
    </DocsShell>
  );
}
