import Foundation

public enum SettingsKey {
    public static let appEditor = "app_editor"
    public static let appPortRangeStart = "app_port_range_start"
    public static let appPortRangeEnd = "app_port_range_end"
    public static let guiHotkey = "gui_hotkey"
    public static let defaultGUIHotkey = "cmd+shift+="
    public static let guiNextShortcut = "gui_next_shortcut"
    public static let defaultGUINextShortcut = "cmd+shift+]"
    public static let guiPreviousShortcut = "gui_previous_shortcut"
    public static let defaultGUIPreviousShortcut = "cmd+shift+["
    public static let guiShowShortcut = "gui_show_shortcut"
    public static let defaultGUIShowShortcut = "cmd+shift+return"
    public static let guiAddProjectShortcut = "gui_add_project_shortcut"
    public static let defaultGUIAddProjectShortcut = "cmd+shift+n"
    public static let guiAddWorkspaceShortcut = "gui_add_workspace_shortcut"
    public static let defaultGUIAddWorkspaceShortcut = "cmd+n"
    public static let guiReloadShortcut = "gui_reload_shortcut"
    public static let defaultGUIReloadShortcut = "cmd+r"
    public static let guiOpenEditorShortcut = "gui_open_editor_shortcut"
    public static let defaultGUIOpenEditorShortcut = "cmd+shift+e"
    public static let guiOpenTerminalShortcut = "gui_open_terminal_shortcut"
    public static let defaultGUIOpenTerminalShortcut = "cmd+shift+t"
    public static let guiOpenFinderShortcut = "gui_open_finder_shortcut"
    public static let defaultGUIOpenFinderShortcut = "cmd+shift+f"
    public static let guiOpenSettingsShortcut = "gui_open_settings_shortcut"
    public static let defaultGUIOpenSettingsShortcut = "cmd+,"
    public static let guiTooltipShortcut = "gui_tooltip_shortcut"
    public static let defaultGUITooltipShortcut = "cmd+shift+i"
    public static let itermFocusPulseColor = "iterm_focus_pulse_color"
    /// Default iTerm2 focus pulse color: amber (~65535, 50000, 0 in AppleScript 16-bit = 255, 195, 0 in 8-bit RGB).
    public static let defaultItermFocusPulseColor = "255,195,0"
}
