import Foundation

/// The text of every generated shell-integration file. Absolute paths are embedded already quoted for the
/// shell that reads the file.
enum SpacesShellIntegrationScripts {
    /// Single-quotes `value` for POSIX sh, zsh, bash and fish (all accept `\'` re-entry as `'\''`).
    static func quoted(_ value: String) -> String { "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'" }

    /// POSIX sh, so it runs wherever Spaces' terminals do (macOS and Linux) with no dependency on the
    /// user's shell.
    ///
    /// It always `exec`s: Spaces identifies agents by the running executable's argv, so the wrapper must
    /// not stay in the process tree. Every marked wrapper directory is skipped, not just this one, because
    /// nested Spaces profiles can put two wrapper directories on PATH and two wrappers exec'ing each other
    /// would loop. `--no-daemon` is a hard error when given twice and is rejected with `--remote`,
    /// `codex agents` and `codex queue`, so those (and an explicit `--no-daemon`, e.g. in a restored
    /// command line) pass through untouched.
    static func codexWrapper() -> String {
        #"""
        #!/bin/sh
        # Generated by Spaces. Runs codex with its own in-process app-server (--no-daemon) so hooks, MCP
        # servers and shell commands see this terminal's environment.
        real=
        oldifs=$IFS
        set -f
        IFS=:
        # The trailing ":" keeps a trailing empty PATH entry (the current directory) from being dropped.
        path_entries="$PATH:"
        for dir in $path_entries; do
          [ -n "$dir" ] || dir=.
          [ -e "$dir/\#(SpacesShellIntegration.wrapperMarkerFileName)" ] && continue
          if [ -f "$dir/codex" ] && [ -x "$dir/codex" ]; then
            real="$dir/codex"
            break
          fi
        done
        IFS=$oldifs
        if [ -z "$real" ]; then
          echo "codex: command not found" >&2
          exit 127
        fi
        for arg in "$@"; do
          case $arg in
            agents | queue | --remote | --remote=* | --no-daemon) exec "$real" "$@" ;;
          esac
        done
        exec "$real" --no-daemon "$@"

        """#
    }

    /// Sourced by zsh because `ZDOTDIR` points at this directory. Restores the user's `ZDOTDIR`, runs the
    /// user's own `.zshenv`, then (interactive shells only) registers the PATH hook. Modeled on Ghostty's
    /// zsh integration.
    static func zshenv(binDirectory: String) -> String {
        #"""
        # Generated by Spaces.
        if [[ -n "${SPACES_USER_ZDOTDIR_SET}" ]]; then
            'builtin' 'export' ZDOTDIR="$SPACES_USER_ZDOTDIR"
        else
            'builtin' 'unset' 'ZDOTDIR'
        fi
        'builtin' 'unset' 'SPACES_USER_ZDOTDIR' 'SPACES_USER_ZDOTDIR_SET'

        {
            # Zsh treats an unset ZDOTDIR as HOME. Unreadable rc files are ignored, as zsh does.
            'builtin' 'typeset' _spaces_file=${ZDOTDIR-$HOME}"/.zshenv"
            [[ ! -r "$_spaces_file" ]] || 'builtin' 'source' '--' "$_spaces_file"
        } always {
            'builtin' 'unset' '_spaces_file'
            if [[ -o 'interactive' ]]; then
                # Moves the wrapper directory to the front of PATH. It runs before each prompt and again
                # right before each command (preexec): hooks the user's rc files register after this file
                # ran (direnv, mise) run after a precmd hook registered here and would otherwise win until
                # the second prompt.
                __spaces_path_hook() {
                    'emulate' '-L' 'zsh'
                    'builtin' 'local' bin=\#(quoted(binDirectory))
                    if [[ "${path[1]}" != "$bin" ]]; then
                        path=("$bin" "${(@)path:#${(b)bin}}")
                    fi
                }
                precmd_functions+=('__spaces_path_hook')
                preexec_functions+=('__spaces_path_hook')

                # Ghostty's own integration (OSC 133 prompt marks, OSC 7 directory reports). Sourced the way
                # Ghostty documents for a manual setup; the terminal sets GHOSTTY_RESOURCES_DIR and leaves
                # every optional feature off.
                if [[ -n "${GHOSTTY_RESOURCES_DIR-}" ]]; then
                    'builtin' 'source' '--' "$GHOSTTY_RESOURCES_DIR/shell-integration/zsh/ghostty-integration"
                fi
            fi
        }

        """#
    }

    /// Read by bash as its `ENV` startup file: Spaces starts bash with `--posix` so bash reads no startup
    /// files itself, and this script restores the user's `ENV`, leaves posix mode, and sources the files
    /// bash would have read. Modeled on Ghostty's bash integration.
    static func bash(binDirectory: String) -> String {
        #"""
        # Generated by Spaces.
        builtin unset ENV
        if [[ -n "${SPACES_USER_ENV_SET}" ]]; then builtin export ENV="$SPACES_USER_ENV"; fi
        builtin unset SPACES_USER_ENV SPACES_USER_ENV_SET

        # Restore bash's default (non-posix) behavior. 'inherit_errexit' is not reset by leaving posix mode.
        builtin set +o posix
        builtin shopt -u inherit_errexit 2>/dev/null

        # Posix mode defaults HISTFILE to ~/.sh_history; keep bash's own history file unless the user
        # exported a HISTFILE themselves.
        if [[ "$HISTFILE" == "$HOME/.sh_history" && ! "$(builtin declare -p HISTFILE)" =~ ^declare\ -[a-zA-Z]*x ]]; then
          HISTFILE="$HOME/.bash_history"
        fi

        # The startup sequence of INVOCATION in bash(1).
        if builtin shopt -q login_shell; then
          [ -r /etc/profile ] && builtin source /etc/profile
          for __spaces_rcfile in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
            [ -r "$__spaces_rcfile" ] && {
              builtin source "$__spaces_rcfile"
              break
            }
          done
        else
          # The system bashrc location is a build-time choice that varies by distro.
          for __spaces_rcfile in /etc/bash.bashrc /etc/bash/bashrc /etc/bashrc; do
            [ -r "$__spaces_rcfile" ] && {
              builtin source "$__spaces_rcfile"
              break
            }
          done
          [ -r "$HOME/.bashrc" ] && builtin source "$HOME/.bashrc"
        fi
        builtin unset __spaces_rcfile

        # Ghostty's own integration (OSC 133 prompt marks, OSC 7 directory reports), sourced the way Ghostty
        # documents for a manual setup; the terminal sets GHOSTTY_RESOURCES_DIR and leaves every optional
        # feature off. It goes before the hook below so that hook stays last in PROMPT_COMMAND.
        if [[ -n "${GHOSTTY_RESOURCES_DIR-}" ]]; then
          builtin source "$GHOSTTY_RESOURCES_DIR/shell-integration/bash/ghostty.bash"
        fi

        # Last in PROMPT_COMMAND so it also wins over hooks the rc files registered. It passes through the
        # status it was given, which is the user's last command status unless an earlier hook changed it.
        __spaces_path_prompt() {
          local ret=$? bin=\#(quoted(binDirectory)) rest
          if [[ "${PATH%%:*}" != "$bin" ]]; then
            rest=":$PATH:"
            while [[ "$rest" == *":$bin:"* ]]; do rest="${rest//":$bin:"/:}"; done
            rest="${rest#:}"
            rest="${rest%:}"
            PATH="$bin${rest:+:$rest}"
          fi
          return $ret
        }
        if [[ "$(builtin declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
          PROMPT_COMMAND+=(__spaces_path_prompt)
        else
          PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}__spaces_path_prompt"
        fi

        """#
    }

    /// Sourced by fish from `fish/vendor_conf.d` because the launch put this data directory on
    /// `XDG_DATA_DIRS`. Restores the user's `XDG_DATA_DIRS` (set or unset), then registers the PATH hook.
    static func fish(binDirectory: String) -> String {
        #"""
        # Generated by Spaces.
        if set -q SPACES_USER_XDG_DATA_DIRS
            set -gx XDG_DATA_DIRS "$SPACES_USER_XDG_DATA_DIRS"
            set -e SPACES_USER_XDG_DATA_DIRS
        else
            set -e XDG_DATA_DIRS
        end

        if status --is-interactive
            # Runs before each prompt and before each command: handlers registered later in config.fish
            # (direnv) run after one registered here and would otherwise win until the next prompt.
            function __spaces_path_hook --on-event fish_prompt --on-event fish_preexec
                set -l bin \#(quoted(binDirectory))
                if test "$PATH[1]" != "$bin"
                    set -l rest
                    for entry in $PATH
                        test "$entry" != "$bin"; and set rest $rest $entry
                    end
                    set -gx PATH $bin $rest
                end
            end

            # Ghostty's own integration (OSC 133 prompt marks, OSC 7 directory reports), sourced the way
            # Ghostty documents for a manual setup; the terminal sets GHOSTTY_RESOURCES_DIR and leaves every
            # optional feature off. Last, because that script ends in `exit`, which also ends this file.
            if set -q GHOSTTY_RESOURCES_DIR
                source "$GHOSTTY_RESOURCES_DIR/shell-integration/fish/vendor_conf.d/ghostty-shell-integration.fish"
            end
        end

        """#
    }
}
