import Foundation

public enum SettingsKey {
    public static let appEditor = "app_editor"
    public static let appTerminalHost = "app_terminal_host"
    public static let defaultAppTerminalHost = TerminalHost.iterm2.rawValue
    public static let appPortRangeStart = "app_port_range_start"
    public static let appPortRangeEnd = "app_port_range_end"
    public static let guiHotkey = "gui_hotkey"
    public static let defaultGUIHotkey = "cmd+alt+="
    public static let guiLeaderHotkey = "gui_leader_hotkey"
    public static let defaultGUILeaderHotkey = "cmd+alt"
    public static let guiDashboardShortcut = "gui_dashboard_shortcut"
    public static let defaultGUIDashboardShortcut = "g"
    public static let guiAddProjectShortcut = "gui_add_project_shortcut"
    public static let defaultGUIAddProjectShortcut = "cmd+shift+n"
    public static let guiAddWorkspaceShortcut = "gui_add_workspace_shortcut"
    public static let defaultGUIAddWorkspaceShortcut = "cmd+n"
    public static let guiReloadShortcut = "gui_reload_shortcut"
    public static let defaultGUIReloadShortcut = "r"
    public static let guiOpenEditorShortcut = "gui_open_editor_shortcut"
    public static let defaultGUIOpenEditorShortcut = "e"
    public static let guiOpenTerminalShortcut = "gui_open_terminal_shortcut"
    public static let defaultGUIOpenTerminalShortcut = "t"
    public static let guiOpenFinderShortcut = "gui_open_finder_shortcut"
    public static let defaultGUIOpenFinderShortcut = "f"
    public static let guiOpenSettingsShortcut = "gui_open_settings_shortcut"
    public static let defaultGUIOpenSettingsShortcut = "cmd+,"
    public static let guiNextShortcut = "gui_next_shortcut"
    public static let defaultGUINextShortcut = "]"
    public static let guiPreviousShortcut = "gui_previous_shortcut"
    public static let defaultGUIPreviousShortcut = "["
    public static let guiWindowShortcut = "gui_window_shortcut"
    public static let defaultGUIWindowShortcut = "cmd+1"
    public static let guiWindowSequenceShortcut = "gui_window_sequence_shortcut"
    public static let defaultGUIWindowSequenceShortcut = "1"
    public static let dashboardDismissedAttentionItems = "dashboard_dismissed_attention_items"
    public static let windowFocusPulseColor = "window_focus_pulse_color"
    /// Default window focus pulse overlay color (8-bit RGB).
    public static let defaultWindowFocusPulseColor = "72,98,110"
    public static let windowFocusPulseEnabled = "window_focus_pulse_enabled"
    public static let defaultWindowFocusPulseEnabled = true
}
