import type { Metadata } from "next";
import { ScreenshotFrame } from "../../components/screenshot-frame";
import { DocsShell } from "../components/docs-shell";

export const metadata: Metadata = {
  title: "Workspace Lifecycle",
  description: "How workspace state changes from create to archive.",
};

export default function WorkspaceLifecycleDocsPage() {
  return (
    <DocsShell
      title="Workspace Lifecycle"
      description="Workspaces are the core runtime unit in Spaceship: they own process templates, browser sessions, status checks, window tracking, and reserved ports."
      pagePath="/docs/workspace-lifecycle"
    >
      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Lifecycle States</h2>
        <ul className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>• `default`: auto-created per project and cannot be archived.</li>
          <li>• `stopped`: persisted workspace with no active runtime indicators.</li>
          <li>• `running`: processes/windows tracked and available for switching.</li>
          <li>• `archived`: hidden from normal lists; worktree removed for git projects.</li>
        </ul>
      </article>

      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Create</h2>
        <p className="mt-2 text-sm leading-7 text-foreground-soft">
          Workspace creation snapshots project-level templates into per-workspace settings,
          runs `setup_script`, and reserves 10 ports.
        </p>
        <ul className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>• Git projects use a worktree directory under `/Users/&lt;username&gt;/spaceship/workspaces/&lt;project&gt;/&lt;dirname&gt;`.</li>
          <li>• `dirname` is an autogenerated unique food-name token per project.</li>
          <li>• Branch creation precedence: local branch, then `origin/&lt;branch&gt;`, then new branch from target branch.</li>
          <li>• Branch is required for Git workspaces.</li>
        </ul>
        <pre className="mt-3 w-full max-w-full min-w-0 overflow-x-auto whitespace-pre-wrap break-words rounded-xl border border-line bg-background-soft/80 p-3 text-xs leading-6 text-foreground">
          <code>{`spaceship workspace create \
  --project-dir /path/to/repo \
  --name feat-auth \
  --branch feat/auth \
  --target-branch main`}</code>
        </pre>
      </article>

      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Launch</h2>
        <p className="mt-2 text-sm leading-7 text-foreground-soft">
          Launch is allowed only when a workspace is stopped. If runtime indicators already
          exist, Spaceship asks you to use restart instead.
        </p>
        <ul className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>• Starts workspace processes in dedicated terminal windows.</li>
          <li>• Opens browser sessions and tracks matching Chrome tabs by URL prefix.</li>
          <li>• Opens the workspace in the preferred editor (if configured).</li>
          <li>• Captures workspace windows so they can be focused later by shortcut.</li>
        </ul>
      </article>

      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Ports Per Workspace</h2>
        <p className="mt-2 text-sm leading-7 text-foreground-soft">
          Each workspace receives ten reserved ports so multiple streams can run in parallel without
          reusing the same local service ports.
        </p>
        <ul className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>• Ports are exposed as `PORT0` through `PORT9` to every workspace process.</li>
          <li>• Port allocation comes from the configured base range in YAML (`port_range`).</li>
          <li>• Reserved ports are retained as workspace runtime state and released on archive.</li>
        </ul>
        <pre className="mt-3 w-full max-w-full min-w-0 overflow-x-auto whitespace-pre-wrap break-words rounded-xl border border-line bg-background-soft/80 p-3 text-xs leading-6 text-foreground">
          <code>{`Workspace: bugfix/login-timeout
PORT0=21001
PORT1=21002
PORT2=21003`}</code>
        </pre>
      </article>

      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Update While Running</h2>
        <ul className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>• Newly added processes start immediately in new terminal windows.</li>
          <li>• Process command changes restart the process in the same terminal window.</li>
          <li>• Newly added browser session URLs open immediately.</li>
          <li>• Workspace overrides remain in SQLite and do not mutate YAML templates.</li>
        </ul>
      </article>

      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Stop and Restart</h2>
        <p className="mt-2 text-sm leading-7 text-foreground-soft">
          Restart runs stop first, then launch, for the same workspace.
        </p>
        <ul className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>• Process groups are interrupted first, then terminated if needed.</li>
          <li>• `stop_script` runs after automatic process termination.</li>
          <li>• Tracked workspace windows are closed (terminals, browsers, editor).</li>
          <li>• Runtime process and window rows are cleared from runtime state.</li>
        </ul>
      </article>

      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Switching Between Workspaces</h2>
        <p className="mt-2 text-sm leading-7 text-foreground-soft">
          Switching workspaces changes active context in one action: windows, process list,
          browser session targets, and status output all follow the selected workspace.
        </p>
        <ol className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>1. Select another running workspace from the sidebar or with next/previous shortcuts.</li>
          <li>2. Activate it to focus the first tracked window (`cmd+shift+return`).</li>
          <li>3. Continue cycling within that workspace using next/previous or `cmd+1..9`.</li>
        </ol>
      </article>

      <article className="rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm">
        <h2 className="text-xl font-semibold tracking-tight">Archive</h2>
        <ul className="mt-3 space-y-2 text-sm leading-7 text-foreground-soft">
          <li>• Default workspace cannot be archived.</li>
          <li>• Archive always runs the same stop flow as restart/stop.</li>
          <li>• For Git projects, archive removes the worktree directory but keeps Git branches.</li>
          <li>• For non-Git projects, archive never deletes the project directory.</li>
          <li>• Reserved workspace ports are released on archive.</li>
        </ul>
        <pre className="mt-3 w-full max-w-full min-w-0 overflow-x-auto whitespace-pre-wrap break-words rounded-xl border border-line bg-background-soft/80 p-3 text-xs leading-6 text-foreground">
          <code>{`spaceship workspace stop --project-dir /path/to/repo --name feat-auth
spaceship workspace restart --project-dir /path/to/repo --name feat-auth
spaceship workspace archive --project-dir /path/to/repo --name feat-auth`}</code>
        </pre>
      </article>

      <article className="grid gap-4 rounded-2xl border border-line bg-surface/82 p-5 backdrop-blur-sm md:grid-cols-2">
        <ScreenshotFrame
          title="Workspace Action Bar"
          caption="Launch/Restart/Stop/Archive controls with state-aware availability."
        />
        <ScreenshotFrame
          title="Workspace Tabs"
          caption="Run, Env, and Settings tabs tied to the selected workspace."
        />
      </article>
    </DocsShell>
  );
}
