#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE_PLIST="$REPO_ROOT/apps/macos/AppVersion.plist"
APP_VERSION_SWIFT="$REPO_ROOT/apps/macos/Sources/workspacecore/AppVersion.swift"
INFO_PLIST="$REPO_ROOT/apps/macos/Sources/SpacesApp/Info.plist"

usage() {
  cat <<'EOF'
Usage: scripts/sync-app-version.sh [--short <version>] [--build <build>] [--feed-url <url>] [--public-ed-key <key>] [--remote-artifact-public-ed-key <key>]

Updates apps/macos/AppVersion.plist and regenerates:
  - apps/macos/Sources/workspacecore/AppVersion.swift
  - apps/macos/Sources/SpacesApp/Info.plist
EOF
}

short_version_set=0
short_version=""
build_version_set=0
build_version=""
feed_url_set=0
feed_url=""
public_ed_key_set=0
public_ed_key=""
remote_artifact_public_ed_key_set=0
remote_artifact_public_ed_key=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --short)
      [[ $# -ge 2 ]] || { echo "--short requires a value" >&2; exit 1; }
      short_version="$2"
      short_version_set=1
      shift 2
      ;;
    --build)
      [[ $# -ge 2 ]] || { echo "--build requires a value" >&2; exit 1; }
      build_version="$2"
      build_version_set=1
      shift 2
      ;;
    --feed-url)
      [[ $# -ge 2 ]] || { echo "--feed-url requires a value" >&2; exit 1; }
      feed_url="$2"
      feed_url_set=1
      shift 2
      ;;
    --public-ed-key)
      [[ $# -ge 2 ]] || { echo "--public-ed-key requires a value" >&2; exit 1; }
      public_ed_key="$2"
      public_ed_key_set=1
      shift 2
      ;;
    --remote-artifact-public-ed-key)
      [[ $# -ge 2 ]] || { echo "--remote-artifact-public-ed-key requires a value" >&2; exit 1; }
      remote_artifact_public_ed_key="$2"
      remote_artifact_public_ed_key_set=1
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

python3 - "$SOURCE_PLIST" "$APP_VERSION_SWIFT" "$INFO_PLIST" \
  "$short_version_set" "$short_version" \
  "$build_version_set" "$build_version" \
  "$feed_url_set" "$feed_url" \
  "$public_ed_key_set" "$public_ed_key" \
  "$remote_artifact_public_ed_key_set" "$remote_artifact_public_ed_key" <<'PY'
import pathlib
import plistlib
import sys

source_plist = pathlib.Path(sys.argv[1])
app_version_swift = pathlib.Path(sys.argv[2])
info_plist = pathlib.Path(sys.argv[3])

arguments = sys.argv[4:]
updates = {
    "CFBundleShortVersionString": (arguments[0] == "1", arguments[1]),
    "CFBundleVersion": (arguments[2] == "1", arguments[3]),
    "SUFeedURL": (arguments[4] == "1", arguments[5]),
    "SUPublicEDKey": (arguments[6] == "1", arguments[7]),
    "SpacesRemoteArtifactPublicEd25519Key": (arguments[8] == "1", arguments[9]),
}

with source_plist.open("rb") as handle:
    metadata = plistlib.load(handle)

for key, (is_set, value) in updates.items():
    if is_set:
        metadata[key] = value

required_keys = [
    "CFBundleShortVersionString",
    "CFBundleVersion",
    "SUFeedURL",
    "SUPublicEDKey",
    "SpacesRemoteArtifactPublicEd25519Key",
]
missing_keys = [key for key in required_keys if key not in metadata]
if missing_keys:
    raise SystemExit(f"Missing required app version metadata: {', '.join(missing_keys)}")

with source_plist.open("wb") as handle:
    plistlib.dump(metadata, handle, fmt=plistlib.FMT_XML, sort_keys=False)

short_version = metadata["CFBundleShortVersionString"]
build_version = metadata["CFBundleVersion"]
feed_url = metadata["SUFeedURL"]
public_ed_key = metadata["SUPublicEDKey"]
remote_artifact_public_ed_key = metadata["SpacesRemoteArtifactPublicEd25519Key"]

def swift_string(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

app_version_swift.write_text(
    f"""/// Generated by `scripts/sync-app-version.sh`. Do not edit by hand.
public enum AppVersion {{
    public static let short = {swift_string(short_version)}
    public static let build = {swift_string(build_version)}
    public static let remoteArtifactPublicKey = {swift_string(remote_artifact_public_ed_key)}

    public static let current = short
}}
""",
    encoding="utf-8",
)

# Update the existing Info.plist in place rather than regenerating it from a template:
# the sync script owns only the version/feed/signing fields, and a template would drop
# any key added to the plist after the template was written (this happened with
# NSAppleEventsUsageDescription).
with info_plist.open("rb") as handle:
    info = plistlib.load(handle)

info["CFBundleShortVersionString"] = short_version
info["CFBundleVersion"] = build_version
info["SUFeedURL"] = feed_url
info["SUPublicEDKey"] = public_ed_key

with info_plist.open("wb") as handle:
    plistlib.dump(info, handle, fmt=plistlib.FMT_XML, sort_keys=False)

print("Synced app version metadata:")
print(f"  short={short_version}")
print(f"  build={build_version}")
print(f"  feed={feed_url}")
PY
