#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE_PLIST="$REPO_ROOT/apps/macos/AppVersion.plist"
APP_VERSION_SWIFT="$REPO_ROOT/apps/macos/Sources/workspacecore/AppVersion.swift"
INFO_PLIST="$REPO_ROOT/apps/macos/Sources/SpacesApp/Info.plist"

usage() {
  cat <<'EOF'
Usage: scripts/sync-app-version.sh [--short <version>] [--build <build>] [--feed-url <url>] [--public-ed-key <key>]

Updates apps/macos/AppVersion.plist and regenerates:
  - apps/macos/Sources/workspacecore/AppVersion.swift
  - apps/macos/Sources/SpacesApp/Info.plist
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --short)
      plutil -replace CFBundleShortVersionString -string "$2" "$SOURCE_PLIST"
      shift 2
      ;;
    --build)
      plutil -replace CFBundleVersion -string "$2" "$SOURCE_PLIST"
      shift 2
      ;;
    --feed-url)
      plutil -replace SUFeedURL -string "$2" "$SOURCE_PLIST"
      shift 2
      ;;
    --public-ed-key)
      plutil -replace SUPublicEDKey -string "$2" "$SOURCE_PLIST"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

short_version="$(plutil -extract CFBundleShortVersionString raw "$SOURCE_PLIST")"
build_version="$(plutil -extract CFBundleVersion raw "$SOURCE_PLIST")"
feed_url="$(plutil -extract SUFeedURL raw "$SOURCE_PLIST")"
public_ed_key="$(plutil -extract SUPublicEDKey raw "$SOURCE_PLIST")"

cat > "$APP_VERSION_SWIFT" <<EOF
/// Generated by \`scripts/sync-app-version.sh\`. Do not edit by hand.
public enum AppVersion {
    public static let short = "$short_version"
    public static let build = "$build_version"

    public static let current = short
}
EOF

cat > "$INFO_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Spaces</string>
    <key>CFBundleExecutable</key>
    <string>SpacesApp</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleIdentifier</key>
    <string>com.spaces.app</string>
    <key>CFBundleShortVersionString</key>
    <string>$short_version</string>
    <key>CFBundleVersion</key>
    <string>$build_version</string>
    <key>SUFeedURL</key>
    <string>$feed_url</string>
    <key>SUPublicEDKey</key>
    <string>$public_ed_key</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
</dict>
</plist>
EOF

echo "Synced app version metadata:"
echo "  short=$short_version"
echo "  build=$build_version"
echo "  feed=$feed_url"
